export const list = [
  {
    id: 1,
    filename: "Cupcakes",
    value: 1,
    flipState: 1,
    clickable: true,
  },
  {
    id: 2,
    filename: "Cupcakes2",
    value: 1,
    flipState: 1,
    clickable: true,
  },
  {
    id: 3,
    filename: "Waffles",
    value: 2,
    flipState: 1,
    clickable: true,
  },
  {
    id: 4,
    filename: "Waffles2",
    value: 2,
    flipState: 1,
    clickable: true,
  },
  {
    id: 5,
    filename: "Earrings",
    value: 3,
    flipState: 1,
    clickable: true,
  },
  {
    id: 6,
    filename: "Earrings2",
    value: 3,
    flipState: 1,
    clickable: true,
  },
  {
    id: 7,
    filename: "Icecream",
    value: 4,
    flipState: 1,
    clickable: true,
  },
  {
    id: 8,
    filename: "Icecream2",
    value: 4,
    flipState: 1,
    clickable: true,
  },
  {
    id: 9,
    filename: "NailPaint",
    value: 5,
    flipState: 1,
    clickable: true,
  },
  {
    id: 10,
    filename: "NailPaint2",
    value: 5,
    flipState: 1,
    clickable: true,
  },
  {
    id: 11,
    filename: "Scrunchie",
    value: 6,
    flipState: 1,
    clickable: true,
  },
  {
    id: 12,
    filename: "Scrunchie2",
    value: 6,
    flipState: 1,
    clickable: true,
  },
];
